server:
  port: 8080
spring:
  application:
    name: native spring
  datasource:
    url: jdbc:h2:file:~/maxilog
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
